version: 2

jobs:
  install-deploy:
    docker:
    - image: cypress/base:10
    working_directory: ~/shopify-theme
    steps:
      - checkout
      - run: 
            name: npm-install
            command: 'npm install'
      # I would normally not use grunt for this. 
      - run: 
          name: make-public-folder
          command: 'mkdir public'
      # Generall a build step would exist here
      # for demo just a zip of the shop to the public folder
      # zip does not exist in the orb. 
      - run: 
          name: update-env
          command: 'apt-get update'
      - run: 
          name: install-zip
          command: 'apt-get install unzip -y && apt-get install zip -y'

      - run: 
          name: generate-zip
          command: 'zip -r public/theme.zip shop/'
      # Note the env vars passed in below
      # SHOPIFY_URL,
      # SHOPIFY_API_KEY
      # SHOPIFY_API_PASSWORD 
      # NGROK_TOKEN
      # Are all required set them in circle, this dos not require the credentials
      - run: 
          name: start-ngrok-and-deploy
          command: 'node circle_scripts/deploy.js --BUILD_NUMBER={{ .Environment.CIRCLE_BUILD_NUM }} --SHOPIFY_URL="$SHOPIFY_URL" --SHOPIFY_API_KEY="$SHOPIFY_API_KEY" --SHOPIFY_API_PASSWORD="$SHOPIFY_API_PASSWORD" --NGROK_TOKEN="$NGROK_TOKEN"' 
      # We will grab the public folder & cypress json we just wrote
      - save_cache:
          key: public-folder-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/shopify-theme/public
            - ~/shopify-theme/cypress.json

  # Run the tests
  run-integration-tests:
    docker:
      - image: cypress/base:10
    working_directory: ~/shopify-theme
    steps: 
      - checkout
      # grab the cache $$
      - restore_cache:
          key: public-folder-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      # Kinda redundant but as we are now using the cypress orb
      # it is kinda good practice to make sure its all up to spec
      - run: 
          name: install-deps
          command: 'npm install'
      # Checks the theme is ready for testing
      - run: 
          name: checkThemeIsready
          command: 'node circle_scripts/checkThemeIsReady.js'
      - run: 
          name: cypress-integration-tests
          command: 'npm run cypress:ci -- --config supportFile=false --record --key=$CYPRESS_RUN_KEY'

# This actually orders and runs the jobs
# Workflows
workflows:
  version: 2
  deploy_theme:
    jobs:
      - install-deploy:
          filters:
            branches:
              only:
                - master
      - run-integration-tests:
          requires: 
            - install-deploy
            
          
